apiVersion: v1
kind: Service
metadata:
    name: bikes-svc 
    labels: 
        app: bikes-app
spec:
    type: NodePort
    ports:
        - port: 3001
          nodePort: 30001
          protocol: TCP
    selector:
        app: bikes-label-for-selector


