apiVersion: v1
kind: Pod
metadata:
  name: "bikeparts-dev-2-bikes-test-connection"
  labels:
    helm.sh/chart: bikes-0.1.0
    app.kubernetes.io/name: bikes
    app.kubernetes.io/instance: bikeparts-dev-2
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['bikeparts-dev-2-bikes:80']
  restartPolicy: Never