apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikeparts-dev-2-bikes-deploy
  labels:
    helm.sh/chart: bikes-0.1.0
    app.kubernetes.io/name: bikes
    app.kubernetes.io/instance: bikeparts-dev-2
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bikes
      app.kubernetes.io/instance: bikeparts-dev-2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bikes
        app.kubernetes.io/instance: bikeparts-dev-2
    spec:
      serviceAccountName: bikeparts-dev-2-bikes
      securityContext:
        {}
      containers:
        - name: bikes
          securityContext:
            {}
          image: "tkoberle/bikes:1.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}