name: CI to Docker hub 
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./bikes
          file: ./Dockerfile
          push: true
          tags: tkoberle/bikeparts:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
